### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LizandroVilDia** [darshan-majithiya/Generate-SRT-File-using-Google-Cloud-s-Speech-to-Text-API#1]
Hi bro! Do you think you can make a video tutorial explaining step by step what to do!?

**Comment by darshan-majithiya** [comment]
Hey! Sorry, currently I can't make a video. But I think you'll understand this clearly if you follow along with my blog on this application - https://medium.com/searce/generate-srt-file-subtitles-using-google-clouds-speech-to-text-api-402b2f1da3bd :)
